from flask import Flask, render_template, request
from pytube import YouTube

app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def home():
    if request.method == 'POST':
        url = request.form['url']
        yt = YouTube(url)
        ys = yt.streams.get_highest_resolution()
        # Download the video to the server's file system
        # using the default filename generated by pytube
        ys.download()
        return f'Successfully downloaded {ys.default_filename}.'
    return render_template('index.html')

if __name__ == '__main__':
    app.run()
